export * from './types';
export * from './quality';
export * from './dedup';
export * from './pipeline';
export { demoConnector } from './demoConnector';
export * from './garmin';
export * from './strava';
export * from './appleHealth';
export * from './openFoodFacts';
export { CONNECTORS, getConnector } from './registry';
export type { ConnectorInfo } from './registry';
