import type { Exercise } from '@supotsu/core';

/**
 * Seed exercise library (Master Prompt P5.5, P36.3). Static reference data used
 * offline and to seed the `exercises` table. Stable ids so sets can reference
 * them regardless of backend.
 */
export const EXERCISE_LIBRARY: Exercise[] = [
  {
    id: 'ex-back-squat',
    name: 'Squat barre',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hamstrings'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-deadlift',
    name: 'Soulevé de terre',
    category: 'strength',
    primaryMuscles: ['back', 'hamstrings', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-bench-press',
    name: 'Développé couché',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-pull-up',
    name: 'Traction',
    category: 'strength',
    primaryMuscles: ['back', 'biceps'],
    secondaryMuscles: ['core'],
    equipment: [],
    level: 'intermediate',
  },
  {
    id: 'ex-push-up',
    name: 'Pompes',
    category: 'strength',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-kb-swing',
    name: 'Kettlebell swing',
    category: 'functional',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'back'],
    equipment: ['kettlebell'],
    level: 'beginner',
  },
  {
    id: 'ex-wall-balls',
    name: 'Wall balls',
    category: 'sport_specific',
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-plank',
    name: 'Gainage',
    category: 'mobility',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },

  // --- Garmin FIT "exercise_category" imports (Master Prompt — Garmin
  // strength-set import) ------------------------------------------------
  // One generic entry per Garmin exercise_category (not per specific
  // movement — Garmin's `category_subtype` gives that finer detail, but
  // the category alone already gives an honest, confident muscle mapping,
  // which is what the recovery silhouette needs). Categories with no
  // single confident muscle mapping (cardio, run, bike, move, pose, ladder,
  // warm_up, banded_exercises, suspension, indoor_row, …) are intentionally
  // left out — their sets are skipped rather than guessed. See
  // packages/connectors/src/garminFit.ts for the category → id lookup.
  {
    id: 'ex-garmin-calf-raise',
    name: 'Mollets (import Garmin)',
    category: 'strength',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-carry',
    name: 'Portage de charge (import Garmin)',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['back', 'glutes'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-chop',
    name: 'Rotation de tronc (import Garmin)',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-core',
    name: 'Gainage dynamique (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-crunch',
    name: 'Crunch (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-curl',
    name: 'Curl biceps (import Garmin)',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-flye',
    name: 'Écarté (import Garmin)',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-hip-raise',
    name: 'Hip thrust (import Garmin)',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-hip-stability',
    name: 'Stabilité de hanche (import Garmin)',
    category: 'mobility',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['core'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-hip-swing',
    name: 'Balancier de hanche (import Garmin)',
    category: 'functional',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['kettlebell'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-hyperextension',
    name: 'Hyperextension lombaire (import Garmin)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-lateral-raise',
    name: 'Élévation latérale (import Garmin)',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-leg-curl',
    name: 'Leg curl (import Garmin)',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-leg-raise',
    name: 'Relevé de jambes (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: ['quads'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-lunge',
    name: 'Fentes (import Garmin)',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-olympic-lift',
    name: 'Haltérophilie (import Garmin)',
    category: 'strength',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-garmin-plyo',
    name: 'Pliométrie (import Garmin)',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves'],
    equipment: [],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-row',
    name: 'Tirage (import Garmin)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-shoulder-press',
    name: 'Développé épaules (import Garmin)',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-shoulder-stability',
    name: 'Stabilité d’épaule (import Garmin)',
    category: 'mobility',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['core'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-shrug',
    name: 'Shrug (import Garmin)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-sit-up',
    name: 'Sit-up (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-total-body',
    name: 'Corps entier (import Garmin)',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-triceps-extension',
    name: 'Extension triceps (import Garmin)',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-battle-rope',
    name: 'Battle rope (import Garmin)',
    category: 'functional',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['back'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-sandbag',
    name: 'Sac lesté (import Garmin)',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-sled',
    name: 'Traîneau (import Garmin)',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-sledge-hammer',
    name: 'Masse (import Garmin)',
    category: 'functional',
    primaryMuscles: ['core', 'shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-tire',
    name: 'Pneu (import Garmin)',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'advanced',
  },
];
