import type { Exercise } from '@supotsu/core';

/**
 * Seed exercise library (Master Prompt P5.5, P36.3). Static reference data used
 * offline and to seed the `exercises` table. Stable ids so sets can reference
 * them regardless of backend.
 */
export const EXERCISE_LIBRARY: Exercise[] = [
  {
    id: 'ex-back-squat',
    name: 'Squat barre',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hamstrings'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-deadlift',
    name: 'Soulevé de terre',
    category: 'strength',
    primaryMuscles: ['back', 'hamstrings', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-bench-press',
    name: 'Développé couché',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-pull-up',
    name: 'Traction',
    category: 'strength',
    primaryMuscles: ['back', 'biceps'],
    secondaryMuscles: ['core'],
    equipment: [],
    level: 'intermediate',
  },
  {
    id: 'ex-push-up',
    name: 'Pompes',
    category: 'strength',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-kb-swing',
    name: 'Kettlebell swing',
    category: 'functional',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'back'],
    equipment: ['kettlebell'],
    level: 'beginner',
  },
  {
    id: 'ex-wall-balls',
    name: 'Wall balls',
    category: 'sport_specific',
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-plank',
    name: 'Gainage',
    category: 'mobility',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },

  // --- Chest ---
  {
    id: 'ex-incline-bench-press',
    name: 'Développé incliné',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-decline-bench-press',
    name: 'Développé décliné',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-dumbbell-bench-press',
    name: 'Développé couché haltères',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-cable-crossover',
    name: 'Écarté à la poulie',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-chest-dip',
    name: 'Dips (pectoraux)',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-machine-chest-press',
    name: 'Développé couché machine',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Back ---
  {
    id: 'ex-lat-pulldown',
    name: 'Tirage vertical',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Tirage horizontal (poulie basse)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-t-bar-row',
    name: 'Rowing T-bar',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-one-arm-dumbbell-row',
    name: 'Rowing haltère unilatéral',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-face-pull',
    name: 'Face pull',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Shoulders ---
  {
    id: 'ex-overhead-press',
    name: 'Développé militaire',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-arnold-press',
    name: 'Développé Arnold',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-lateral-raise-db',
    name: 'Élévation latérale haltères',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-front-raise',
    name: 'Élévation frontale',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Oiseau (deltoïde postérieur)',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Biceps ---
  {
    id: 'ex-barbell-curl',
    name: 'Curl barre',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-dumbbell-curl',
    name: 'Curl haltères',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-hammer-curl',
    name: 'Curl marteau',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-preacher-curl',
    name: 'Curl pupitre',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-concentration-curl',
    name: 'Curl concentration',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Triceps ---
  {
    id: 'ex-skull-crusher',
    name: 'Extension triceps allongé (skull crusher)',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-triceps-pushdown',
    name: 'Extension triceps à la poulie',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-triceps-dip',
    name: 'Dips (triceps)',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-overhead-triceps-extension',
    name: 'Extension triceps nuque',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Quads ---
  {
    id: 'ex-leg-press',
    name: 'Presse à cuisses',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg extension',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-front-squat',
    name: 'Squat avant',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-lunge',
    name: 'Fentes avant',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Fente bulgare',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-goblet-squat',
    name: 'Squat gobelet',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['kettlebell'],
    level: 'beginner',
  },

  // --- Hamstrings ---
  {
    id: 'ex-romanian-deadlift',
    name: 'Soulevé de terre roumain',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'back'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-leg-curl-machine',
    name: 'Leg curl machine',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-good-morning',
    name: 'Good morning',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['back', 'glutes'],
    equipment: ['gym'],
    level: 'advanced',
  },

  // --- Glutes ---
  {
    id: 'ex-hip-thrust',
    name: 'Hip thrust barre',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-glute-bridge',
    name: 'Pont fessier',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-cable-kickback',
    name: 'Kickback à la poulie',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Calves ---
  {
    id: 'ex-standing-calf-raise',
    name: 'Mollets debout',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-seated-calf-raise',
    name: 'Mollets assis',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },

  // --- Core ---
  {
    id: 'ex-planche',
    name: 'Planche',
    category: 'mobility',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-side-plank',
    name: 'Planche latérale',
    category: 'mobility',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-hanging-leg-raise',
    name: 'Relevé de jambes suspendu',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-russian-twist',
    name: 'Rotation russe',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-ab-wheel',
    name: 'Roue abdominale',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-cable-woodchop',
    name: 'Woodchop à la poulie',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },

  // --- Functional / full body ---
  {
    id: 'ex-burpee',
    name: 'Burpees',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-thruster',
    name: 'Thruster',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['quads', 'shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-clean-and-press',
    name: 'Épaulé-jeté',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-farmers-carry',
    name: "Farmer's walk",
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['core', 'back'],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-box-jump',
    name: 'Box jump',
    category: 'functional',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'calves'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-mountain-climber',
    name: 'Mountain climbers',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['quads'],
    equipment: [],
    level: 'beginner',
  },

  // --- Garmin FIT "exercise_category" imports (Master Prompt — Garmin
  // strength-set import) ------------------------------------------------
  // One generic entry per Garmin exercise_category (not per specific
  // movement — Garmin's `category_subtype` gives that finer detail, but
  // the category alone already gives an honest, confident muscle mapping,
  // which is what the recovery silhouette needs). Categories with no
  // single confident muscle mapping (cardio, run, bike, move, pose, ladder,
  // warm_up, banded_exercises, suspension, indoor_row, …) are intentionally
  // left out — their sets are skipped rather than guessed. See
  // packages/connectors/src/garminFit.ts for the category → id lookup.
  {
    id: 'ex-garmin-calf-raise',
    name: 'Mollets (import Garmin)',
    category: 'strength',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-carry',
    name: 'Portage de charge (import Garmin)',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['back', 'glutes'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-chop',
    name: 'Rotation de tronc (import Garmin)',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-core',
    name: 'Gainage dynamique (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-crunch',
    name: 'Crunch (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-curl',
    name: 'Curl biceps (import Garmin)',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-flye',
    name: 'Écarté (import Garmin)',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-hip-raise',
    name: 'Hip thrust (import Garmin)',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-hip-stability',
    name: 'Stabilité de hanche (import Garmin)',
    category: 'mobility',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['core'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-hip-swing',
    name: 'Balancier de hanche (import Garmin)',
    category: 'functional',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['kettlebell'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-hyperextension',
    name: 'Hyperextension lombaire (import Garmin)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-lateral-raise',
    name: 'Élévation latérale (import Garmin)',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-leg-curl',
    name: 'Leg curl (import Garmin)',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-leg-raise',
    name: 'Relevé de jambes (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: ['quads'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-lunge',
    name: 'Fentes (import Garmin)',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-olympic-lift',
    name: 'Haltérophilie (import Garmin)',
    category: 'strength',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'advanced',
  },
  {
    id: 'ex-garmin-plyo',
    name: 'Pliométrie (import Garmin)',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves'],
    equipment: [],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-row',
    name: 'Tirage (import Garmin)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-shoulder-press',
    name: 'Développé épaules (import Garmin)',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-shoulder-stability',
    name: 'Stabilité d’épaule (import Garmin)',
    category: 'mobility',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['core'],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-shrug',
    name: 'Shrug (import Garmin)',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-sit-up',
    name: 'Sit-up (import Garmin)',
    category: 'strength',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: [],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-total-body',
    name: 'Corps entier (import Garmin)',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-triceps-extension',
    name: 'Extension triceps (import Garmin)',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'beginner',
  },
  {
    id: 'ex-garmin-battle-rope',
    name: 'Battle rope (import Garmin)',
    category: 'functional',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['back'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-sandbag',
    name: 'Sac lesté (import Garmin)',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-sled',
    name: 'Traîneau (import Garmin)',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-sledge-hammer',
    name: 'Masse (import Garmin)',
    category: 'functional',
    primaryMuscles: ['core', 'shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['gym'],
    level: 'intermediate',
  },
  {
    id: 'ex-garmin-tire',
    name: 'Pneu (import Garmin)',
    category: 'functional',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['gym'],
    level: 'advanced',
  },
];

/**
 * The subset of EXERCISE_LIBRARY meant to be picked by hand when building a
 * session. Excludes the Garmin-import-only entries above — those exist
 * purely so an imported FIT set has a muscle mapping, and their generic
 * "(import Garmin)" names would just be clutter in a manual exercise picker.
 */
export const PICKABLE_EXERCISES: Exercise[] = EXERCISE_LIBRARY.filter((e) => !e.id.startsWith('ex-garmin-'));

/** Fast id → exercise lookup — same source, indexed for O(1) reads (screenshot-import resolution, history display). */
export const EXERCISE_BY_ID: Record<string, Exercise> = Object.fromEntries(EXERCISE_LIBRARY.map((e) => [e.id, e]));
